// <auto-generated />
using EmpManagementWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmpManagementWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201202155330_IncludePhotoPathColumn")]
    partial class IncludePhotoPathColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("EmpManagementWebApp.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Department = 2,
                            Email = "jrm@mymail.com",
                            Name = "Jyoti Ranjan"
                        },
                        new
                        {
                            Id = 2,
                            Department = 4,
                            Email = "supdey@mymail.com",
                            Name = "Supratim Dey"
                        },
                        new
                        {
                            Id = 3,
                            Department = 5,
                            Email = "sayan@mymail.com",
                            Name = "Sayan Dash"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
